# 2/c. Removing viewers from grantee list with content update
# - I'm a publisher
# - I remove viewers from the grantee list of the ACT content
# - The content is updated
# - The removed viewers can't access the latest version of content anymore
# - The removed viewers can access an older version of the content, the version up until the moment they were removed
# - The existing viewers can access the content still, including the latest version
