# 4. Viewer access revoked without content change
# - I'm a viewer
# - I had access to the content until now
# - My access to the content got revoked
# - The content is unchanged
# - I can access the content still


# 4. Viewer access revoked with content update
# - I'm a viewer
# - I had access to the content until now
# - My access to the content got revoked
# - The content is updated
# - I can't access versions of the content that were uploaded after I lost access
